const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

  //admin

  //GET employee infor login
  GET_EMPLOYEE_INFOR_START: "GET_EMPLOYEE_INFOR_START",
  GET_EMPLOYEE_INFOR_SUCCESS: "GET_EMPLOYEE_INFOR_SUCCESS",
  GET_EMPLOYEE_INFOR_FAILED: "GET_EMPLOYEE_INFOR_FAILED",
  //get all employ
  GET_ALL_EMPLOYEE_START: "GET_ALL_EMPLOYEE_START",
  GET_ALL_EMPLOYEE_SUCCESS: "GET_ALL_EMPLOYEE_SUCCESS",
  GET_ALL_EMPLOYEE_FAILED: "GET_ALL_EMPLOYEE_FAILED",
  //get all Movie
  GET_ALL_MOVIE_START: "GET_ALL_MOVIE_START",
  GET_ALL_MOVIE_SUCCESS: "GET_ALL_MOVIE_SUCCESS",
  GET_ALL_MOVIE_FAILED: "GET_ALL_MOVIE_FAILED",

  //Get requred movie
  GET_ALL_REQUIRED_MOVIE_START: "GET_ALL_REQUIRED_MOVIE_START",
  GET_ALL_REQUIRED_MOVIE_SUCCESS: "GET_ALL_REQUIRED_MOVIE_SUCCESS",
  GET_ALL_REQUIRED_MOVIE_FAILED: "GET_ALL_REQUIRED_MOVIE_FAILED",
  //DELETE employee
  DELETECT_EMPLOYEE_START: "DELETECT_EMPLOYEE_START",
  DELETECT_EMPLOYEE_SUCCESS: "DELETECT_EMPLOYEE_SUCCESS",
  DELETECT_EMPLOYEE_FAILED: "DELETECT_EMPLOYEE_FAILED",
  //GET ALL SCHEDULETIME
  GET_ALL_SCHEDULE_TIME_START: "GET_ALL_SCHEDULE_TIME_START",
  GET_ALL_SCHEDULE_TIME_SUCCESS: "GET_ALL_SCHEDULE_TIME_SUCCESS",
  GET_ALL_SCHEDULE_TIME_FAILED: "GET_ALL_SCHEDULE_TIME_FAILED",
  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",
});

export default actionTypes;
